name: Lint & Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
